###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: EasyAdmin-memcached

    mysql:
      image: mysql:8.0
      container_name: EasyAdmin-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD= 'root'
        - MYSQL_DATABASE= 'EasyAdmin'
        - MYSQL_USER= 'root'
        - MYSQL_PASSWORD= #'root' #  in case mysql dont run remove 'root'
      ports:
        - "3308:3306"

    mariadb:
      image: mariadb:10.4
      container_name: EasyAdmin-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=EasyAdmin
        - MYSQL_USER=
        - MYSQL_PASSWORD=
      ports:
        - "3309:3306"

  #    phpmyadmin:
  #      image: phpmyadmin/phpmyadmin
  #      container_name: EasyAdmin-phpmyadmin
  #      working_dir: /application
  #      environment:
  #        PMA_ARBITRARY: 1
  #        MYSQL_USER: root
  #        MYSQL_PASSWORD: root
  #        MYSQL_ROOT_PASSWORD: root
  #      ports:
  #        - "80:80"
  #      links:
  #        - "mysql:mysql"

    webserver:
      image: nginx:alpine
      container_name: EasyAdmin-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: EasyAdmin-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

